---
# tasks file for roles/prometheus


- name: Create prometheus group
  group:
    name: "{{ prometheus_group }}"
    system: true

- name: Create prometheus user
  user:
    name: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    shell: /sbin/nologin
    system: true
    create_home: false

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "0755"
  loop:
    - "{{ prometheus_conf_dir }}"
    - "{{ prometheus_data_dir }}"

- name: Download prometheus tarball
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    mode: "0644"

- name: Extract prometheus
  unarchive:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/tmp"
    remote_src: true

- name: Install prometheus binaries
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "{{ prometheus_bin_dir }}/{{ item }}"
    mode: "0755"
    remote_src: true
  loop:
    - prometheus
    - promtool

- name: Deploy prometheus config
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_conf_dir }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "0644"
  notify: restart prometheus

- name: Validate prometheus config (promtool)
  command: "{{ prometheus_bin_dir }}/promtool check config {{ prometheus_conf_dir }}/prometheus.yml"
  changed_when: false

- name: Deploy systemd unit
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    mode: "0644"
  notify:
    - daemon-reload
    - restart prometheus

- name: Ensure prometheus is enabled and started
  systemd:
    name: prometheus
    state: started
    enabled: true
