---
- name: Install postgres packages
  ansible.builtin.dnf:
    name: "{{ dr_postgres_packages }}"
    state: present

- name: Initialize postgres database (only once)
  ansible.builtin.command: postgresql-setup --initdb
  args:
    creates: /var/lib/pgsql/data/PG_VERSION

- name: Enable and start postgresql
  ansible.builtin.systemd:
    name: postgresql
    enabled: true
    state: started
