---
# defaults file for roles/node_exporter

node_exporter_version: "1.10.2"
node_exporter_arch: "linux-amd64"
node_exporter_user: "node_exporter"
node_exporter_group: "node_exporter"
node_exporter_install_dir: "/usr/local/bin"
node_exporter_listen_address: "0.0.0.0:9100"
node_exporter_textfile_enabled: false
node_exporter_textfile_dir: "/var/lib/node_exporter/textfile_collector"