- name: Install node_exporter on all servers
  hosts: all
  roles:
    - node_exporter


- name: Install Prometheus on monitoring server
  hosts: monitoring
  become: true
  roles:
    - prometheus

- name: Install Grafana on monitoring server
  hosts: monitoring
  become: true
  roles:
    - grafana

- name: Install Loki on monitoring server
  hosts: monitoring
  become: true
  roles:
    - loki