- name: Generate postgres SSH keys on DB nodes
  hosts: pgsql_db
  gather_facts: false
  roles:
    - pg_ssh_keygen

- name: Register DB postgres keys on pgBackRest repo
  hosts: pgbackrest_repo
  gather_facts: false
  roles:
    - pg_ssh_authorized_keys
